version: 2
jobs:
  build:
    docker:
      - image: "circleci/node:latest"
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: bootstrap
          command: npm run bootstrap
      - run:
          name: test
          command: npm run test
